# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: keymetrics/pm2:latest-alpine

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: VSWhere
      uses: heaths/setup-msbuild@c4f3bee
        
    # - name: Check PowerShell version
    #   run: $PSVersionTable
    
    # - name: Check Get-FileHash syntax
    #   run: Get-FileHash -?
    
    # - name: Test Get-FileHash on README.md
    #   run: (Get-FileHash -Path "README.md" -Algorithm "SHA512").Hash
    
    # - name: Get PowerShell version from cmd
    #   shell: cmd
    #   run: powershell $PSVersionTable
    
    # - name: Test Get-FileHash on README.md from cmd
    #   shell: cmd
    #   run: powershell (Get-FileHash -Path "README.md" -Algorithm "SHA512").Hash
    
    - name: Test container usage
      run: pm2 -v
